(define (problem Dieci-Campi)
  (:domain CAMPI)
  (:objects traA1 traA2 traS1 traS2 - trattore
        aratro1 aratro2 - aratro
        seminatore1 seminatore2 - seminatore
        contadino1 contadino2 - contadino
        cam1 cam2 cam3 cam4 cam5 cam6 cam7 cam8 cam9 cam10 - campo)
  (:init
   (contad contadino1)
   (contad contadino2)
   (field cam1)
   (field cam2)
   (field cam3)
   (field cam4)
   (field cam5)
   (field cam6)
   (field cam7)
   (field cam8)
   (field cam9)
   (field cam10)
   (tra traA1)
   (tra traA2)
   (tra traS1)
   (tra traS2)
   (tra-ara traA1)
   (tra-ara traA2)
   (tra-semina traS1)
   (tra-semina traS2)
   (plow aratro1)
   (plow aratro2)
   (sower seminatore1)
   (sower seminatore2)
   (connesso cam1 cam2)
   (connesso cam2 cam1)
   (connesso cam2 cam3)
   (connesso cam3 cam2)
   (connesso cam3 cam4)
   (connesso cam4 cam3)
   (connesso cam4 cam5)
   (connesso cam5 cam4)
   (connesso cam5 cam2)
   (connesso cam2 cam5)
   (connesso cam5 cam6)
   (connesso cam6 cam5)
   (connesso cam6 cam7)
   (connesso cam7 cam6)
   (connesso cam7 cam8)
   (connesso cam8 cam7)
   (connesso cam8 cam1)
   (connesso cam1 cam8)
   (connesso cam8 cam9)
   (connesso cam9 cam8)
   (connesso cam9 cam10)
   (connesso cam10 cam9)
   (connesso cam5 cam1)
   (connesso cam1 cam5)
   (at traA1 cam1);; dynamic predicates
   (at traA2 cam5)
   (at traS1 cam1)
   (at traS2 cam4)
   (at aratro1 cam3)
   (at aratro2 cam8)
   (at seminatore1 cam2)
   (at seminatore2 cam6)
   (at contadino1 cam1)
   (at contadino2 cam5)
   )
 
  (:goal (and
   (annaffiato cam6)
   (annaffiato cam7)
   (annaffiato cam8)
   (annaffiato cam9)
   (annaffiato cam10)
   (seminato cam1)
   (seminato cam1)
   (seminato cam2)
   (seminato cam3)
   (seminato cam4)
   (seminato cam5)))
  )